name: validation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out cjson source code
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          apt update && apt install sudo
          sudo apt update
          sudo apt install -y build-essential cmake autoconf libtool libtool-bin pkg-config
      - name: Install Valgrind
        run: |
          sudo apt install -y valgrind
      - name: Install libcheck
        run: |
          cd /tmp
          wget https://github.com/libcheck/check/releases/download/0.15.2/check-0.15.2.tar.gz
          tar xf check*.tar.gz && cd check-0.15.2
          autoreconf --install
          ./configure
          sudo make install
          sudo ldconfig
      - name: Build cjson
        run: |
          cd ${{ github.workspace }}
          mkdir cmake-build && cd cmake-build
          cmake init ..
          make
      - name: Run unit tests
        run: |
          ./cmake-build/tests/unit_tests/unit_tests --allow-fork
      - name: Run unit tests (Valgrind)
        run: |
          valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./cmake-build/tests/unit_tests/unit_tests --exclude-tags bad
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
